import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/app/components/Header';
import { Footer } from '@/app/components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-screen flex justify-center bg-white'>
          <div className='w-full flex flex-col justify-center max-w-6xl gap-10'>
            <Header />
            {children}
            <Footer />
          </div>
        </div>

      </body>
    </html>
  )
}
